# adapté de https://dev.to/alissonzampietro/the-amazing-journey-of-docker-compose-17lj
version: '3.8'
services:
    #launch all 3 services
    api-service:
        #build the container of the python flask api 
        build: .
        #set build directory to the current directory
        volumes:
            #define the volumes, maps the 'api/' directory on the host to 'usr/src/app/' in the container
            - ./api/:/usr/src/app/
        ports:
            #map the port oh the container to the real port on the host machine here it just maps 5000 to 5000
            - 5000:3333 
    mariadb:  
        container_name: mariadb_EXPRESS
        image: mariadb
        restart: always
        environment:
            MYSQL_ROOT_PASSWORD: root
            MYSQL_DATABASE: mydatabase
            MYSQL_USER: maria
            MYSQL_PASSWORD: maria
        ports:
            - "3306:3306"
        volumes:
            - ./mariadb:/var/lib/mysql
            - ./init.sql:/docker-entrypoint-initdb.d/init.sql

    adminer:
        #build an adminer instance from the adminer image
        image: adminer
        #pull the adminer image from docker hub
        container_name: adminer_EXPRESS
        #naming the container
        depends_on:
            #declare a dependency to the mariadb service
            - mariadb
        ports:
            #maps the container port to the host machine port
            - 8080:8080